name: Testes Regressivos Agendados

on:
  schedule:
    - cron: '* 7 * * 1-5'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar o Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Instalar o Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

      - name: Instalar o ChromeDriver
        uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run Tests
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci

      - name: Gerar Relatorio
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatorio de testes
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-execution
          path: "**/formated-report/"

      - name: Enviar notificacao Slack com SUCESSO
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: notify-test-in-slack
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://w7.pngwing.com/pngs/367/375/png-transparent-success-kid-child-computer-icons-oh-baby-child-face-toddler-thumbnail.png
          SLACK_MESSAGE: 'Teste AGENDADO executado com SUCESSO! :dardo_no_alvo:'
          SLACK_TITLE: 'Status dos testes :olho_balão:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificacao Slack com FALHA
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: notify-test-in-slack
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://w7.pngwing.com/pngs/814/922/png-transparent-inside-out-sadness-http-404-error-message-web-browser-computer-servers-pixar-miscellaneous-pixar-electric-blue-thumbnail.png
          SLACK_MESSAGE: 'Teste AGENDADO executado com FALHA! :choramingando:'
          SLACK_TITLE: 'Status dos testes :olho_balão:'
          SLACK_USERNAME: FALHA